version: '3.8'

services:
  consul:
    image: consul:1.10.12
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - mynetwork
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - consul

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "3003:3003"
    networks:
      - mynetwork
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "3005:3005"
    networks:
      - mynetwork
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "3004:3004"
    networks:
      - mynetwork
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "3002:3002"
    networks:
      - mynetwork
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


networks:
  mynetwork:
    driver: bridge
